version: '3'
services:
  vendure_builder:
    build: 
      context: .
      dockerfile: ./Dockerfile.builder
    image: vendure_builder
  vendure_server:
    build:
      context: .
      dockerfile: ./Dockerfile.runner
    image: vendure/server
    depends_on:
      - vendure_builder
